tail: false

environment: development

tag: development

pid_file: tmp/pids/appctl.pid

log_file: log/appctl.log

mongrel2:
  recv: tcp://127.0.0.1:20101
  send: tcp://127.0.0.1:20102
  uuid: 534a36f1-5fcb-4636-8aa9-749fae727ad5

epoll: true
